# Use the same base image as Django
FROM python:3.10.12

# Set the working directory
WORKDIR /app

# Copy the project files into the container
COPY . /app/

# Install requirements for both Django and Celery
COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

# Start the Celery worker
# CMD ["celery", "-A", "django_celery", "worker", "--loglevel=info"]