# Generated by Django 5.1.8 on 2025-04-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_newsletter_subscriber_delete_substriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='created_at',
            new_name='sent_at',
        ),
    ]
