# Generated by Django 5.1.8 on 2025-04-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_rename_created_at_newsletter_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='sent_at',
            field=models.DateTimeField(),
        ),
    ]
